from .tutor_personas import TUTOR_PERSONAS, FUNCTIONING_LEVEL_ADAPTATIONS

PERSONA_REGISTRY: dict[str, str] = {}

for sku, persona in TUTOR_PERSONAS.items():
    name_lower = persona["name"].lower()
    subject_lower = persona["subject"].lower()
    PERSONA_REGISTRY[sku] = sku
    PERSONA_REGISTRY[name_lower] = sku
    PERSONA_REGISTRY[subject_lower] = sku

PERSONA_REGISTRY["math"] = "ADDON_TUTOR_MATH"
PERSONA_REGISTRY["ela"] = "ADDON_TUTOR_ELA"
PERSONA_REGISTRY["reading"] = "ADDON_TUTOR_ELA"
PERSONA_REGISTRY["writing"] = "ADDON_TUTOR_ELA"
PERSONA_REGISTRY["history"] = "ADDON_TUTOR_HISTORY"
PERSONA_REGISTRY["social studies"] = "ADDON_TUTOR_SOCIAL_STUDIES"
PERSONA_REGISTRY["coding"] = "ADDON_TUTOR_CODING"
PERSONA_REGISTRY["computer science"] = "ADDON_TUTOR_CODING"
PERSONA_REGISTRY["technology"] = "ADDON_TUTOR_CODING"
PERSONA_REGISTRY["speech"] = "ADDON_TUTOR_SPEECH"
PERSONA_REGISTRY["communication"] = "ADDON_TUTOR_SPEECH"
PERSONA_REGISTRY["sel"] = "ADDON_TUTOR_SEL"
PERSONA_REGISTRY["emotions"] = "ADDON_TUTOR_SEL"
PERSONA_REGISTRY["geography"] = "ADDON_TUTOR_SOCIAL_STUDIES"
PERSONA_REGISTRY["world cultures"] = "ADDON_TUTOR_SOCIAL_STUDIES"
PERSONA_REGISTRY["music"] = "ADDON_TUTOR_ARTS"
PERSONA_REGISTRY["rhythm"] = "ADDON_TUTOR_ARTS"
PERSONA_REGISTRY["arts"] = "ADDON_TUTOR_ARTS"
PERSONA_REGISTRY["pe"] = "ADDON_TUTOR_PE_HEALTH"
PERSONA_REGISTRY["health"] = "ADDON_TUTOR_PE_HEALTH"
PERSONA_REGISTRY["fitness"] = "ADDON_TUTOR_PE_HEALTH"
PERSONA_REGISTRY["physical education"] = "ADDON_TUTOR_PE_HEALTH"
PERSONA_REGISTRY["languages"] = "ADDON_TUTOR_LANGUAGES"
PERSONA_REGISTRY["spanish"] = "ADDON_TUTOR_LANGUAGES"
PERSONA_REGISTRY["french"] = "ADDON_TUTOR_LANGUAGES"
PERSONA_REGISTRY["bilingual"] = "ADDON_TUTOR_LANGUAGES"
PERSONA_REGISTRY["engineering"] = "ADDON_TUTOR_STEM_DESIGN"
PERSONA_REGISTRY["design"] = "ADDON_TUTOR_STEM_DESIGN"
PERSONA_REGISTRY["stem"] = "ADDON_TUTOR_STEM_DESIGN"
PERSONA_REGISTRY["life skills"] = "ADDON_TUTOR_LIFE_SKILLS"
PERSONA_REGISTRY["executive function"] = "ADDON_TUTOR_LIFE_SKILLS"
PERSONA_REGISTRY["transition"] = "ADDON_TUTOR_LIFE_SKILLS"
PERSONA_REGISTRY["creative writing"] = "ADDON_TUTOR_CREATIVE_WRITING"
PERSONA_REGISTRY["storytelling"] = "ADDON_TUTOR_CREATIVE_WRITING"
PERSONA_REGISTRY["poetry"] = "ADDON_TUTOR_CREATIVE_WRITING"


def resolve_persona_sku(identifier: str) -> str | None:
    return PERSONA_REGISTRY.get(identifier.lower())
