import {
  ASSESSMENT_SUBJECTS,
  BRAIN_SUBJECTS,
  TUTOR_SUBJECTS,
  HOMEWORK_SUBJECTS,
  LEARNING_SUBJECTS,
  ENGAGEMENT_SUBJECTS,
  BILLING_SUBJECTS,
  COMMS_SUBJECTS,
  IDENTITY_SUBJECTS,
  ADMIN_SUBJECTS,
  INTEGRATIONS_SUBJECTS,
  STATUS_SUBJECTS,
  RESEARCH_SUBJECTS,
  FEATURE_FLAG_SUBJECTS,
} from "./schemas/index.js";

export const SUBJECTS = {
  ...ASSESSMENT_SUBJECTS,
  ...BRAIN_SUBJECTS,
  ...TUTOR_SUBJECTS,
  ...HOMEWORK_SUBJECTS,
  ...LEARNING_SUBJECTS,
  ...ENGAGEMENT_SUBJECTS,
  ...BILLING_SUBJECTS,
  ...COMMS_SUBJECTS,
  ...IDENTITY_SUBJECTS,
  ...ADMIN_SUBJECTS,
  ...INTEGRATIONS_SUBJECTS,
  ...STATUS_SUBJECTS,
  ...RESEARCH_SUBJECTS,
  ...FEATURE_FLAG_SUBJECTS,
} as const;

export type EventName = keyof typeof SUBJECTS;
export type NatsSubject = (typeof SUBJECTS)[EventName];
