#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# HOTFIX DEPLOY — Assessment Proxy + Service Discovery Fix
# ═══════════════════════════════════════════════════════════════════
#
# Deploys only the changed services (identity-svc, web, i18n-svc)
# to production without creating a full release. Unchanged services
# remain on v1.2.1.
#
# Prerequisites:
#   - Docker with Buildx
#   - Authenticated to GHCR: echo $GHCR_TOKEN | docker login ghcr.io -u <user> --password-stdin
#   - kubectl configured with production kubeconfig
#   - Helm 3.x installed
#   - Run from the repository root
#
# Usage:
#   ./scripts/hotfix-deploy.sh              # build, push, and deploy
#   ./scripts/hotfix-deploy.sh --build-only # build and push images only
#   ./scripts/hotfix-deploy.sh --deploy-only # deploy with existing images
#
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Configuration ──
IMAGE_PREFIX="ghcr.io/artpromedia"
NAMESPACE="aivo"
RELEASE_NAME="aivo-learning-saas"
CURRENT_RELEASE="v1.2.1"   # tag for unchanged services
HOTFIX_TAG="hotfix-$(git rev-parse --short=7 HEAD)"

# ── Parse flags ──
BUILD=true
DEPLOY=true
case "${1:-}" in
  --build-only)  DEPLOY=false ;;
  --deploy-only) BUILD=false ;;
  --help|-h)
    head -22 "$0" | tail -19
    exit 0
    ;;
esac

echo "═══════════════════════════════════════════════"
echo "  AIVO Hotfix Deploy"
echo "  Commit:  $(git rev-parse --short HEAD)"
echo "  Tag:     $HOTFIX_TAG"
echo "  Base:    $CURRENT_RELEASE"
echo "═══════════════════════════════════════════════"
echo ""

# ── Preflight checks ──
if [ "$(git status --porcelain)" ]; then
  echo "WARNING: Working tree has uncommitted changes."
  echo "Images will be built from the current working tree."
  echo ""
fi

if $BUILD; then
  if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Docker is not running" >&2
    exit 1
  fi
fi

if $DEPLOY; then
  if ! kubectl cluster-info >/dev/null 2>&1; then
    echo "ERROR: kubectl cannot reach the cluster" >&2
    echo "Set KUBECONFIG or configure ~/.kube/config" >&2
    exit 1
  fi
  if ! helm version >/dev/null 2>&1; then
    echo "ERROR: helm is not installed" >&2
    exit 1
  fi
fi

# ═══════════════════════════════════════════════
# Stage 1: Build & Push Changed Images
# ═══════════════════════════════════════════════
if $BUILD; then
  echo "── Stage 1: Building changed images ──"
  echo ""

  # identity-svc — backend service (context: repo root)
  echo "[1/3] Building identity-svc..."
  docker buildx build \
    --platform linux/amd64 \
    -t "${IMAGE_PREFIX}/identity-svc:${HOTFIX_TAG}" \
    -f services/identity-svc/Dockerfile \
    --push \
    .
  echo "  ✓ identity-svc pushed as ${HOTFIX_TAG}"
  echo ""

  # web — Next.js app (context: repo root)
  echo "[2/3] Building web..."
  docker buildx build \
    --platform linux/amd64 \
    -t "${IMAGE_PREFIX}/web:${HOTFIX_TAG}" \
    -f apps/web/Dockerfile \
    --build-arg NEXT_PUBLIC_API_URL=https://app.aivolearning.com \
    --push \
    .
  echo "  ✓ web pushed as ${HOTFIX_TAG}"
  echo ""

  # i18n-svc — backend service (context: repo root)
  echo "[3/3] Building i18n-svc..."
  docker buildx build \
    --platform linux/amd64 \
    -t "${IMAGE_PREFIX}/i18n-svc:${HOTFIX_TAG}" \
    -f services/i18n-svc/Dockerfile \
    --push \
    .
  echo "  ✓ i18n-svc pushed as ${HOTFIX_TAG}"
  echo ""

  echo "All images pushed to GHCR."
  echo ""
fi

# ═══════════════════════════════════════════════
# Stage 2: Generate image-tags override YAML
# ═══════════════════════════════════════════════
if $DEPLOY; then
  echo "── Stage 2: Preparing Helm override ──"

  TMPFILE=$(mktemp /tmp/hotfix-image-tags.XXXXXX.yaml)

  # Unchanged services stay on v1.2.1, changed services get hotfix tag
  cat > "$TMPFILE" <<EOYAML
# Auto-generated by hotfix-deploy.sh — $(date -u +"%Y-%m-%d %H:%M UTC")
# Hotfix: $HOTFIX_TAG | Base: $CURRENT_RELEASE

# ── Changed services (hotfix) ──
identity-svc:
  image:
    repository: ${IMAGE_PREFIX}/identity-svc
    tag: "${HOTFIX_TAG}"
web:
  image:
    repository: ${IMAGE_PREFIX}/web
    tag: "${HOTFIX_TAG}"
i18n-svc:
  image:
    repository: ${IMAGE_PREFIX}/i18n-svc
    tag: "${HOTFIX_TAG}"

# ── Unchanged services (pinned to ${CURRENT_RELEASE}) ──
billing-svc:
  image:
    repository: ${IMAGE_PREFIX}/billing-svc
    tag: "${CURRENT_RELEASE}"
family-svc:
  image:
    repository: ${IMAGE_PREFIX}/family-svc
    tag: "${CURRENT_RELEASE}"
integrations-svc:
  image:
    repository: ${IMAGE_PREFIX}/integrations-svc
    tag: "${CURRENT_RELEASE}"
admin-svc:
  image:
    repository: ${IMAGE_PREFIX}/admin-svc
    tag: "${CURRENT_RELEASE}"
learning-svc:
  image:
    repository: ${IMAGE_PREFIX}/learning-svc
    tag: "${CURRENT_RELEASE}"
engagement-svc:
  image:
    repository: ${IMAGE_PREFIX}/engagement-svc
    tag: "${CURRENT_RELEASE}"
comms-svc:
  image:
    repository: ${IMAGE_PREFIX}/comms-svc
    tag: "${CURRENT_RELEASE}"
tutor-svc:
  image:
    repository: ${IMAGE_PREFIX}/tutor-svc
    tag: "${CURRENT_RELEASE}"
status-page-svc:
  image:
    repository: ${IMAGE_PREFIX}/status-page-svc
    tag: "${CURRENT_RELEASE}"
research-svc:
  image:
    repository: ${IMAGE_PREFIX}/research-svc
    tag: "${CURRENT_RELEASE}"
research-worker:
  image:
    repository: ${IMAGE_PREFIX}/research-svc
    tag: "${CURRENT_RELEASE}"
ai-svc:
  image:
    repository: ${IMAGE_PREFIX}/ai-svc
    tag: "${CURRENT_RELEASE}"
brain-svc:
  image:
    repository: ${IMAGE_PREFIX}/brain-svc
    tag: "${CURRENT_RELEASE}"
assessment-svc:
  image:
    repository: ${IMAGE_PREFIX}/assessment-svc
    tag: "${CURRENT_RELEASE}"
marketing:
  image:
    repository: ${IMAGE_PREFIX}/marketing
    tag: "${CURRENT_RELEASE}"
EOYAML

  echo "  Image overrides written to $TMPFILE"
  echo ""

  # ═══════════════════════════════════════════════
  # Stage 3: Helm Upgrade
  # ═══════════════════════════════════════════════
  echo "── Stage 3: Deploying via Helm ──"
  echo ""

  # Check current release status
  STATUS=$(helm status "$RELEASE_NAME" -n "$NAMESPACE" -o json 2>/dev/null | grep -o '"status":"[^"]*"' | cut -d'"' -f4 || echo "not-found")
  echo "  Current Helm release status: $STATUS"

  if [ "$STATUS" = "pending-install" ] || [ "$STATUS" = "pending-upgrade" ] || [ "$STATUS" = "pending-rollback" ]; then
    echo "  WARNING: Helm release is stuck in '$STATUS' — rolling back first"
    helm rollback "$RELEASE_NAME" 0 -n "$NAMESPACE" --timeout 5m || true
  fi

  echo ""
  echo "  Running helm upgrade..."
  echo "  Values: hetzner-production.yaml + hotfix image tags"
  echo ""

  helm dependency build infra/helm

  helm upgrade --install "$RELEASE_NAME" infra/helm \
    -f infra/helm/values/hetzner-production.yaml \
    -f "$TMPFILE" \
    -n "$NAMESPACE" \
    --atomic \
    --timeout 15m \
    --wait

  echo ""
  echo "  ✓ Helm upgrade complete"
  echo ""

  # ═══════════════════════════════════════════════
  # Stage 4: Verify Rollout
  # ═══════════════════════════════════════════════
  echo "── Stage 4: Verifying rollout ──"
  echo ""

  CHANGED_SVCS=(identity-svc web i18n-svc)
  FAILED=0

  for svc in "${CHANGED_SVCS[@]}"; do
    echo -n "  $svc: "
    if kubectl rollout status deployment/"$svc" -n "$NAMESPACE" --timeout=120s 2>/dev/null; then
      # Check image tag
      RUNNING_TAG=$(kubectl get deployment "$svc" -n "$NAMESPACE" \
        -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null | grep -o '[^:]*$')
      echo "    Running tag: $RUNNING_TAG"
    else
      echo "    FAILED"
      FAILED=$((FAILED + 1))
    fi
  done

  echo ""
  if [ "$FAILED" -gt 0 ]; then
    echo "ERROR: $FAILED service(s) failed rollout!"
    echo "To rollback: helm rollback $RELEASE_NAME -n $NAMESPACE"
    exit 1
  fi

  # ═══════════════════════════════════════════════
  # Stage 5: Smoke Test
  # ═══════════════════════════════════════════════
  echo "── Stage 5: Smoke tests ──"
  echo ""

  # Health check identity-svc via internal service
  echo -n "  identity-svc /health: "
  HEALTH=$(kubectl exec -n "$NAMESPACE" deploy/identity-svc -- \
    wget -qO- http://localhost:3001/health 2>/dev/null || echo "FAILED")
  echo "$HEALTH"

  # Health check web
  echo -n "  web /api/health: "
  HEALTH=$(kubectl exec -n "$NAMESPACE" deploy/web -- \
    wget -qO- http://localhost:3000/api/health 2>/dev/null || echo "FAILED")
  echo "$HEALTH"

  # Check assessment proxy route exists
  echo -n "  assessment-proxy route: "
  RESP=$(kubectl exec -n "$NAMESPACE" deploy/identity-svc -- \
    wget -qO- --spider http://localhost:3001/api/assessment/health 2>&1 || true)
  if echo "$RESP" | grep -qE "200|404"; then
    echo "OK (route registered)"
  else
    echo "WARNING — route may not be registered"
  fi

  echo ""
  rm -f "$TMPFILE"
fi

echo "═══════════════════════════════════════════════"
echo "  Hotfix deploy complete!"
echo ""
echo "  Changed services:"
echo "    identity-svc  → ${HOTFIX_TAG}"
echo "    web           → ${HOTFIX_TAG}"
echo "    i18n-svc      → ${HOTFIX_TAG}"
echo "  Unchanged:       → ${CURRENT_RELEASE}"
echo ""
echo "  Rollback command:"
echo "    helm rollback ${RELEASE_NAME} -n ${NAMESPACE}"
echo "═══════════════════════════════════════════════"
