default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: true
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/aivo_mobile.ipa",
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end

  desc "Upload a new release to the App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: true
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: "../build/ios/ipa/aivo_mobile.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
