/**
 * Seeded Item Banks for Baseline Assessment
 *
 * Each item has IRT parameters (difficulty, discrimination) and supports
 * multiple presentation formats based on functioning level.
 */

import type { IrtItem, FunctioningLevelFormat } from "./irt.js";

const ALL_FORMATS: FunctioningLevelFormat[] = ["STANDARD", "SIMPLIFIED", "PICTURE_BASED", "OBSERVATION", "MILESTONE"];
const STANDARD_FORMATS: FunctioningLevelFormat[] = ["STANDARD", "SIMPLIFIED"];
const ACCESSIBLE_FORMATS: FunctioningLevelFormat[] = ["STANDARD", "SIMPLIFIED", "PICTURE_BASED"];

// ─── MATH Item Bank ─────────────────────────────────────────────────────────────

const MATH_ITEMS: IrtItem[] = [
  // Very easy items (b ~ -2.5 to -1.5)
  {
    id: "math-001",
    domain: "MATH",
    skill: "counting",
    difficulty: -2.5,
    discrimination: 1.2,
    prompt: "How many apples are there? 🍎🍎🍎",
    type: "multiple_choice",
    options: ["2", "3", "4", "5"],
    correctAnswer: "3",
    formats: ALL_FORMATS,
  },
  {
    id: "math-002",
    domain: "MATH",
    skill: "counting",
    difficulty: -2.0,
    discrimination: 1.0,
    prompt: "Count the stars: ⭐⭐⭐⭐⭐",
    type: "multiple_choice",
    options: ["3", "4", "5", "6"],
    correctAnswer: "5",
    formats: ALL_FORMATS,
  },
  {
    id: "math-003",
    domain: "MATH",
    skill: "number-recognition",
    difficulty: -2.3,
    discrimination: 1.1,
    prompt: "Which number comes after 3?",
    type: "multiple_choice",
    options: ["2", "4", "5", "1"],
    correctAnswer: "4",
    formats: ALL_FORMATS,
  },
  // Easy items (b ~ -1.5 to -0.5)
  {
    id: "math-004",
    domain: "MATH",
    skill: "addition",
    difficulty: -1.5,
    discrimination: 1.3,
    prompt: "What is 2 + 3?",
    type: "multiple_choice",
    options: ["4", "5", "6", "7"],
    correctAnswer: "5",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "math-005",
    domain: "MATH",
    skill: "addition",
    difficulty: -1.0,
    discrimination: 1.4,
    prompt: "What is 7 + 5?",
    type: "multiple_choice",
    options: ["11", "12", "13", "10"],
    correctAnswer: "12",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "math-006",
    domain: "MATH",
    skill: "subtraction",
    difficulty: -0.8,
    discrimination: 1.2,
    prompt: "What is 9 - 4?",
    type: "multiple_choice",
    options: ["3", "4", "5", "6"],
    correctAnswer: "5",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "math-007",
    domain: "MATH",
    skill: "comparison",
    difficulty: -1.2,
    discrimination: 1.1,
    prompt: "Which number is bigger: 15 or 9?",
    type: "multiple_choice",
    options: ["15", "9"],
    correctAnswer: "15",
    formats: ALL_FORMATS,
  },
  // Medium items (b ~ -0.5 to 0.5)
  {
    id: "math-008",
    domain: "MATH",
    skill: "multiplication",
    difficulty: 0.0,
    discrimination: 1.5,
    prompt: "What is 6 × 4?",
    type: "multiple_choice",
    options: ["20", "22", "24", "26"],
    correctAnswer: "24",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-009",
    domain: "MATH",
    skill: "multiplication",
    difficulty: 0.3,
    discrimination: 1.4,
    prompt: "What is 8 × 7?",
    type: "multiple_choice",
    options: ["54", "56", "58", "63"],
    correctAnswer: "56",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-010",
    domain: "MATH",
    skill: "division",
    difficulty: 0.2,
    discrimination: 1.3,
    prompt: "What is 36 ÷ 6?",
    type: "multiple_choice",
    options: ["4", "5", "6", "7"],
    correctAnswer: "6",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-011",
    domain: "MATH",
    skill: "place-value",
    difficulty: -0.3,
    discrimination: 1.2,
    prompt: "In the number 472, what digit is in the tens place?",
    type: "multiple_choice",
    options: ["4", "7", "2", "0"],
    correctAnswer: "7",
    formats: STANDARD_FORMATS,
  },
  // Hard items (b ~ 0.5 to 1.5)
  {
    id: "math-012",
    domain: "MATH",
    skill: "fractions",
    difficulty: 0.8,
    discrimination: 1.6,
    prompt: "What is 1/4 + 1/2?",
    type: "multiple_choice",
    options: ["1/6", "2/4", "3/4", "1/3"],
    correctAnswer: "3/4",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-013",
    domain: "MATH",
    skill: "fractions",
    difficulty: 1.0,
    discrimination: 1.5,
    prompt: "Which fraction is equivalent to 2/3?",
    type: "multiple_choice",
    options: ["3/4", "4/6", "4/9", "3/6"],
    correctAnswer: "4/6",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-014",
    domain: "MATH",
    skill: "decimals",
    difficulty: 1.2,
    discrimination: 1.4,
    prompt: "What is 0.75 + 0.5?",
    type: "multiple_choice",
    options: ["1.15", "1.20", "1.25", "1.30"],
    correctAnswer: "1.25",
    formats: STANDARD_FORMATS,
  },
  // Very hard items (b ~ 1.5 to 2.5)
  {
    id: "math-015",
    domain: "MATH",
    skill: "algebra",
    difficulty: 1.8,
    discrimination: 1.7,
    prompt: "If 3x + 7 = 22, what is x?",
    type: "multiple_choice",
    options: ["3", "4", "5", "6"],
    correctAnswer: "5",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-016",
    domain: "MATH",
    skill: "algebra",
    difficulty: 2.0,
    discrimination: 1.6,
    prompt: "Solve for y: 2y - 8 = 3y + 2",
    type: "multiple_choice",
    options: ["-10", "-6", "6", "10"],
    correctAnswer: "-10",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-017",
    domain: "MATH",
    skill: "geometry",
    difficulty: 1.5,
    discrimination: 1.3,
    prompt: "A triangle has angles of 60° and 80°. What is the third angle?",
    type: "multiple_choice",
    options: ["30°", "40°", "50°", "60°"],
    correctAnswer: "40°",
    formats: STANDARD_FORMATS,
  },
  {
    id: "math-018",
    domain: "MATH",
    skill: "ratios",
    difficulty: 2.2,
    discrimination: 1.5,
    prompt: "If the ratio of cats to dogs is 3:5 and there are 15 cats, how many dogs are there?",
    type: "multiple_choice",
    options: ["20", "25", "30", "9"],
    correctAnswer: "25",
    formats: STANDARD_FORMATS,
  },
];

// ─── ELA Item Bank ──────────────────────────────────────────────────────────────

const ELA_ITEMS: IrtItem[] = [
  // Very easy (b ~ -2.5 to -1.5)
  {
    id: "ela-001",
    domain: "ELA",
    skill: "letter-recognition",
    difficulty: -2.5,
    discrimination: 1.1,
    prompt: "Which letter comes after B in the alphabet?",
    type: "multiple_choice",
    options: ["A", "C", "D", "E"],
    correctAnswer: "C",
    formats: ALL_FORMATS,
  },
  {
    id: "ela-002",
    domain: "ELA",
    skill: "letter-sounds",
    difficulty: -2.0,
    discrimination: 1.0,
    prompt: "What sound does the letter 'S' make?",
    type: "multiple_choice",
    options: ["sss", "fff", "mmm", "zzz"],
    correctAnswer: "sss",
    formats: ALL_FORMATS,
  },
  {
    id: "ela-003",
    domain: "ELA",
    skill: "sight-words",
    difficulty: -2.2,
    discrimination: 1.2,
    prompt: "Which word says 'the'?",
    type: "multiple_choice",
    options: ["they", "the", "then", "there"],
    correctAnswer: "the",
    formats: ALL_FORMATS,
  },
  // Easy (b ~ -1.5 to -0.5)
  {
    id: "ela-004",
    domain: "ELA",
    skill: "phonics",
    difficulty: -1.3,
    discrimination: 1.3,
    prompt: "Which word rhymes with 'cat'?",
    type: "multiple_choice",
    options: ["dog", "hat", "cup", "run"],
    correctAnswer: "hat",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "ela-005",
    domain: "ELA",
    skill: "vocabulary",
    difficulty: -1.0,
    discrimination: 1.2,
    prompt: "What does 'happy' mean?",
    type: "multiple_choice",
    options: ["Sad", "Feeling good and glad", "Angry", "Tired"],
    correctAnswer: "Feeling good and glad",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "ela-006",
    domain: "ELA",
    skill: "reading-comprehension",
    difficulty: -0.7,
    discrimination: 1.4,
    prompt: "The dog is big and brown. What color is the dog?",
    type: "multiple_choice",
    options: ["White", "Black", "Brown", "Red"],
    correctAnswer: "Brown",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "ela-007",
    domain: "ELA",
    skill: "spelling",
    difficulty: -0.5,
    discrimination: 1.1,
    prompt: "Which word is spelled correctly?",
    type: "multiple_choice",
    options: ["becuz", "becuse", "because", "becaus"],
    correctAnswer: "because",
    formats: STANDARD_FORMATS,
  },
  // Medium (b ~ -0.5 to 0.5)
  {
    id: "ela-008",
    domain: "ELA",
    skill: "grammar",
    difficulty: 0.0,
    discrimination: 1.3,
    prompt: "Choose the correct sentence:",
    type: "multiple_choice",
    options: [
      "She don't like pizza.",
      "She doesn't like pizza.",
      "She doesn't likes pizza.",
      "Her doesn't like pizza.",
    ],
    correctAnswer: "She doesn't like pizza.",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-009",
    domain: "ELA",
    skill: "reading-comprehension",
    difficulty: 0.3,
    discrimination: 1.5,
    prompt: "Sam woke up early. He put on his uniform and packed his backpack. Where is Sam most likely going?",
    type: "multiple_choice",
    options: ["The beach", "School", "A restaurant", "Bed"],
    correctAnswer: "School",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-010",
    domain: "ELA",
    skill: "vocabulary",
    difficulty: 0.5,
    discrimination: 1.4,
    prompt: "What does 'reluctant' mean?",
    type: "multiple_choice",
    options: ["Eager", "Unwilling or hesitant", "Happy", "Angry"],
    correctAnswer: "Unwilling or hesitant",
    formats: STANDARD_FORMATS,
  },
  // Hard (b ~ 0.5 to 1.5)
  {
    id: "ela-011",
    domain: "ELA",
    skill: "grammar",
    difficulty: 0.8,
    discrimination: 1.5,
    prompt: "Identify the adverb: 'She quickly ran to the store.'",
    type: "multiple_choice",
    options: ["She", "quickly", "ran", "store"],
    correctAnswer: "quickly",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-012",
    domain: "ELA",
    skill: "reading-comprehension",
    difficulty: 1.0,
    discrimination: 1.6,
    prompt: "The author uses the phrase 'heart of stone' to suggest the character is:",
    type: "multiple_choice",
    options: ["Very strong", "Unfeeling and cold", "Made of rock", "Brave"],
    correctAnswer: "Unfeeling and cold",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-013",
    domain: "ELA",
    skill: "writing",
    difficulty: 1.2,
    discrimination: 1.4,
    prompt: "Which is the best topic sentence for a paragraph about recycling?",
    type: "multiple_choice",
    options: [
      "Recycling is good.",
      "Recycling reduces waste and conserves natural resources for future generations.",
      "People recycle things.",
      "Trash goes in the garbage.",
    ],
    correctAnswer: "Recycling reduces waste and conserves natural resources for future generations.",
    formats: STANDARD_FORMATS,
  },
  // Very hard (b ~ 1.5 to 2.5)
  {
    id: "ela-014",
    domain: "ELA",
    skill: "literary-analysis",
    difficulty: 1.8,
    discrimination: 1.7,
    prompt: "In a story, the weather mirrors the character's emotions. This technique is called:",
    type: "multiple_choice",
    options: ["Foreshadowing", "Pathetic fallacy", "Hyperbole", "Alliteration"],
    correctAnswer: "Pathetic fallacy",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-015",
    domain: "ELA",
    skill: "vocabulary",
    difficulty: 2.0,
    discrimination: 1.5,
    prompt: "Choose the word that best completes: 'The politician's speech was filled with _____, saying much but meaning little.'",
    type: "multiple_choice",
    options: ["eloquence", "rhetoric", "platitudes", "anecdotes"],
    correctAnswer: "platitudes",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-016",
    domain: "ELA",
    skill: "grammar",
    difficulty: 1.5,
    discrimination: 1.3,
    prompt: "Which sentence uses a semicolon correctly?",
    type: "multiple_choice",
    options: [
      "I went to the store; and bought milk.",
      "I went to the store; I bought milk.",
      "I went; to the store I bought milk.",
      "I went to; the store and bought milk.",
    ],
    correctAnswer: "I went to the store; I bought milk.",
    formats: STANDARD_FORMATS,
  },
  {
    id: "ela-017",
    domain: "ELA",
    skill: "literary-analysis",
    difficulty: 2.3,
    discrimination: 1.6,
    prompt: "An unreliable narrator is most effective when the reader:",
    type: "multiple_choice",
    options: [
      "Trusts everything the narrator says",
      "Gradually realizes the narrator's perspective is skewed",
      "Knows the narrator is lying from the start",
      "Ignores the narrator completely",
    ],
    correctAnswer: "Gradually realizes the narrator's perspective is skewed",
    formats: STANDARD_FORMATS,
  },
];

// ─── SCIENCE Item Bank ──────────────────────────────────────────────────────────

const SCIENCE_ITEMS: IrtItem[] = [
  // Very easy (b ~ -2.5 to -1.5)
  {
    id: "sci-001",
    domain: "SCIENCE",
    skill: "living-things",
    difficulty: -2.5,
    discrimination: 1.0,
    prompt: "Which one is a living thing?",
    type: "multiple_choice",
    options: ["Rock", "Tree", "Chair", "Water"],
    correctAnswer: "Tree",
    formats: ALL_FORMATS,
  },
  {
    id: "sci-002",
    domain: "SCIENCE",
    skill: "senses",
    difficulty: -2.2,
    discrimination: 1.1,
    prompt: "Which body part do you use to hear?",
    type: "multiple_choice",
    options: ["Eyes", "Ears", "Nose", "Hands"],
    correctAnswer: "Ears",
    formats: ALL_FORMATS,
  },
  {
    id: "sci-003",
    domain: "SCIENCE",
    skill: "weather",
    difficulty: -2.0,
    discrimination: 1.0,
    prompt: "What falls from clouds when it rains?",
    type: "multiple_choice",
    options: ["Snow", "Water", "Sand", "Leaves"],
    correctAnswer: "Water",
    formats: ALL_FORMATS,
  },
  // Easy (b ~ -1.5 to -0.5)
  {
    id: "sci-004",
    domain: "SCIENCE",
    skill: "habitats",
    difficulty: -1.3,
    discrimination: 1.2,
    prompt: "Where do fish live?",
    type: "multiple_choice",
    options: ["In trees", "In water", "Underground", "In the sky"],
    correctAnswer: "In water",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "sci-005",
    domain: "SCIENCE",
    skill: "plants",
    difficulty: -1.0,
    discrimination: 1.3,
    prompt: "What do plants need to grow? (Choose the best answer)",
    type: "multiple_choice",
    options: ["Sunlight, water, and soil", "Only water", "Only sunlight", "Candy"],
    correctAnswer: "Sunlight, water, and soil",
    formats: ACCESSIBLE_FORMATS,
  },
  {
    id: "sci-006",
    domain: "SCIENCE",
    skill: "states-of-matter",
    difficulty: -0.7,
    discrimination: 1.2,
    prompt: "What happens to ice when you heat it?",
    type: "multiple_choice",
    options: ["It gets bigger", "It melts into water", "It stays the same", "It turns into gas immediately"],
    correctAnswer: "It melts into water",
    formats: ACCESSIBLE_FORMATS,
  },
  // Medium (b ~ -0.5 to 0.5)
  {
    id: "sci-007",
    domain: "SCIENCE",
    skill: "solar-system",
    difficulty: 0.0,
    discrimination: 1.4,
    prompt: "Which planet is closest to the Sun?",
    type: "multiple_choice",
    options: ["Earth", "Venus", "Mercury", "Mars"],
    correctAnswer: "Mercury",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-008",
    domain: "SCIENCE",
    skill: "food-chains",
    difficulty: 0.3,
    discrimination: 1.3,
    prompt: "In a food chain, a producer is:",
    type: "multiple_choice",
    options: ["An animal that eats other animals", "A plant that makes its own food", "A mushroom", "A predator"],
    correctAnswer: "A plant that makes its own food",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-009",
    domain: "SCIENCE",
    skill: "earth-science",
    difficulty: 0.2,
    discrimination: 1.2,
    prompt: "What causes day and night?",
    type: "multiple_choice",
    options: ["The Moon moving", "Earth rotating on its axis", "The Sun moving around Earth", "Clouds blocking the Sun"],
    correctAnswer: "Earth rotating on its axis",
    formats: STANDARD_FORMATS,
  },
  // Hard (b ~ 0.5 to 1.5)
  {
    id: "sci-010",
    domain: "SCIENCE",
    skill: "chemistry",
    difficulty: 0.8,
    discrimination: 1.5,
    prompt: "What is the chemical formula for water?",
    type: "multiple_choice",
    options: ["CO2", "H2O", "NaCl", "O2"],
    correctAnswer: "H2O",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-011",
    domain: "SCIENCE",
    skill: "physics",
    difficulty: 1.0,
    discrimination: 1.4,
    prompt: "What force keeps us on the ground?",
    type: "multiple_choice",
    options: ["Magnetism", "Friction", "Gravity", "Tension"],
    correctAnswer: "Gravity",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-012",
    domain: "SCIENCE",
    skill: "biology",
    difficulty: 1.2,
    discrimination: 1.5,
    prompt: "Photosynthesis is the process by which plants:",
    type: "multiple_choice",
    options: [
      "Absorb water from roots",
      "Convert sunlight into food (glucose)",
      "Release oxygen at night",
      "Grow taller each day",
    ],
    correctAnswer: "Convert sunlight into food (glucose)",
    formats: STANDARD_FORMATS,
  },
  // Very hard (b ~ 1.5 to 2.5)
  {
    id: "sci-013",
    domain: "SCIENCE",
    skill: "genetics",
    difficulty: 1.8,
    discrimination: 1.6,
    prompt: "DNA is best described as:",
    type: "multiple_choice",
    options: [
      "A type of cell",
      "A molecule that carries genetic instructions",
      "A type of protein",
      "An organelle in the cell",
    ],
    correctAnswer: "A molecule that carries genetic instructions",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-014",
    domain: "SCIENCE",
    skill: "physics",
    difficulty: 2.0,
    discrimination: 1.5,
    prompt: "Newton's Third Law states that for every action there is:",
    type: "multiple_choice",
    options: ["No reaction", "An equal and opposite reaction", "A stronger reaction", "A delayed reaction"],
    correctAnswer: "An equal and opposite reaction",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-015",
    domain: "SCIENCE",
    skill: "chemistry",
    difficulty: 2.3,
    discrimination: 1.7,
    prompt: "In the periodic table, elements in the same group have:",
    type: "multiple_choice",
    options: [
      "The same number of protons",
      "Similar chemical properties",
      "The same atomic mass",
      "Identical electron configurations",
    ],
    correctAnswer: "Similar chemical properties",
    formats: STANDARD_FORMATS,
  },
  {
    id: "sci-016",
    domain: "SCIENCE",
    skill: "biology",
    difficulty: 1.5,
    discrimination: 1.4,
    prompt: "Mitochondria are known as the 'powerhouse of the cell' because they:",
    type: "multiple_choice",
    options: [
      "Store genetic information",
      "Produce ATP (energy) for the cell",
      "Break down waste products",
      "Control cell division",
    ],
    correctAnswer: "Produce ATP (energy) for the cell",
    formats: STANDARD_FORMATS,
  },
];

export const ITEM_BANK: IrtItem[] = [...MATH_ITEMS, ...ELA_ITEMS, ...SCIENCE_ITEMS];

export const DOMAINS = ["MATH", "ELA", "SCIENCE"] as const;
export type Domain = (typeof DOMAINS)[number];

/**
 * Filter item bank by functioning level format compatibility
 */
export function getItemsForFunctioningLevel(
  level: import("./irt.js").FunctioningLevelFormat,
): IrtItem[] {
  return ITEM_BANK.filter((item) => item.formats.includes(level));
}

/**
 * Get items for a specific domain
 */
export function getItemsByDomain(domain: Domain): IrtItem[] {
  return ITEM_BANK.filter((item) => item.domain === domain);
}

/**
 * Get items for a specific domain and functioning level
 */
export function getItemsByDomainAndLevel(
  domain: Domain,
  level: import("./irt.js").FunctioningLevelFormat,
): IrtItem[] {
  return ITEM_BANK.filter((item) => item.domain === domain && item.formats.includes(level));
}
